name: StormCore
main: org.stormrealms.stormcore.StormCore
version: 1.0
description: "Core plugin"
api-version: 1.13
depends: [HolographicDisplays, ProtocolLib]
commands:
  sc:
    description: sc.
    usage: /sc
  test:
    description: test command
    usage: /test